# 服务器配置
server:
  port: 20000

#spring配置
spring:
  #数据源配置
  datasource:
    # 自动执行sql
    druid:
      # JDBC 配置
      url: jdbc:mysql://127.0.0.1:3306/cat_guild?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 连接池配置
      # 监控配置
      initial-size: 1  # 初始化大小
      min-idle: 1  # 最小
      max-active: 10   # 最大
      max-wait: 6000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 2000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 600000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位是毫秒

      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      keep-alive: true
      phy-max-use-count: 500

      filters: stat  # 配置监控统计拦截的filters
    embedded-database-connection: NONE

# 日志配置
logging:
  config: classpath:log/logback.xml
