#server:
#  port: 20000
#
##spring配置
#spring:
#  #数据源配置
#  datasource:
#    # 自动执行sql
#    url: jdbc:mysql://127.0.0.1:3306/catguild_auth?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 连接池
#    hikari:
#      connection-timeout: 60000
#      validation-timeout: 3000
#      idle-timeout: 60000
#      login-timeout: 5
#      max-lifetime: 60000
#      maximum-pool-size: 10
#      minimum-idle: 10
#      read-only: false
#
#
## 日志配置
#logging:
#  config: classpath:log/logback-test.xml
spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: catguild@qq.com
    password: rfumcekfphkecajg


##邮箱配置
##平台地址，这里用的是qq邮箱，使用其他邮箱请更换
#spring.mail.host=smtp.qq.com
##端口号
#spring.mail.port=XXX
##发送邮件的邮箱地址：改成自己的邮箱
#spring.mail.username=xxxxxxxxxxx
##发送短信后它给你的授权码 填写到这里
#spring.mail.password=xxxxxxxxxxxx
##与发件邮箱一致
#spring.mail.from=xxxxxxxxxxx