name: business-ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'catguild-business/**'
  #pull_request:
  #  branches: [ main ]

jobs:
  push_to_registry:
    name: CI-Auth
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17 and Cache Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew :catguild-business:jib
