name: network-ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'catguild-network/**'
  #pull_request:
  #  branches: [ main ]

jobs:
  push_to_registry:
    name: CI-Network
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: catguild-network/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catguild-network:main
          # 缓存配置
          cache-from: type=gha
          cache-to: type=gha,mode=min
