name: system-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'catguild-system/**'
  #pull_request:
  #  branches: [ main ]

jobs:
  push_to_registry:
    name: CI-Auth
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Cache gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Download Gradle packages
        run: |
          chmod +x ./gradlew
          ./gradlew :catguild-system:build --no-daemon

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew :catguild-system:jib
