name: ci

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew :catguild-gateway:jib
